# Generated by Django 3.2.18 on 2023-12-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shemsWebapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('num_bedrooms', models.IntegerField()),
                ('num_occupants', models.IntegerField()),
                ('area', models.IntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shemsWebapp.customer')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shemsWebapp.location')),
            ],
            options={
                'db_table': 'customerlocation',
            },
        ),
    ]
