# Generated by Django 3.2.18 on 2023-12-16 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shemsWebapp', '0002_customerlocation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('model_num', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('model_type', models.CharField(max_length=50)),
                ('properties', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'model',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shemsWebapp.location')),
                ('model_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number', to='shemsWebapp.devicemodel')),
                ('model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='shemsWebapp.devicemodel')),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
