# Generated by Django 3.2.18 on 2023-12-16 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shemsWebapp', '0003_device_devicemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'managed': False},
        ),
    ]
