# Generated by Django 3.2.18 on 2023-12-16 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shemsWebapp', '0004_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={},
        ),
    ]
